In [6]:
import pandas as pd
file_path_corrected = '/content/movie.xls'

df = pd.read_csv(file_path_corrected)

In [8]:
# 1.
missing_values = df['duration'].isnull().sum()
missing_values

15

In [10]:
# 2.
median_duration = df['duration'].median()
df['duration'].fillna(median_duration, inplace=True)
missing_values = df['duration'].isnull().sum()
missing_values

0

In [12]:
# 3.
df['genres_count'] = df['genres'].apply(lambda x: len(x.split('|')))
average_genres = df['genres_count'].mean()
average_genres

2.87606583382907

In [21]:
#4.
df['genre_count'] = df['genres'].apply(lambda x: len(x.split('|')))

max_genres = df['genre_count'].max()

max_genre_movies = df[df['genre_count'] == max_genres]

max_genre_movies[['movie_title', 'genres', 'genre_count']]

,movie_title,genres,genre_count
902,Anastasia,Adventure|Animation|Drama|Family|Fantasy|Music...,8
1387,Reindeer Games,Action|Adventure|Crime|Drama|Family|Fantasy|Ro...,8
2340,Dylan Dog: Dead of Night,Action|Comedy|Crime|Fantasy|Horror|Mystery|Sci...,8
3539,Alpha and Omega 4: The Legend of the Saw Tooth...,Action|Adventure|Animation|Comedy|Drama|Family...,8

In [15]:
# 5.
all_genres = df['genres'].str.split('|').explode()
most_common= all_genres.mode()[0]
most_common

'Drama'

In [20]:
# 6.
df['budget'] = df['budget'].str.replace('$', '').astype(float)


filtered_df = df[(df['title_year'] >= 2014) & (df['title_year'] <= 2016)]


pivot_table = filtered_df.pivot_table(values='budget', index='country', columns='title_year', aggfunc='sum', fill_value=0)

pivot_table

<ipython-input-20-ecb8017ed548>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['budget'] = df['budget'].str.replace('$', '').astype(float)

title_year          2014.0      2015.0      2016.0
country
Australia        147500000   160000000           0
Bahamas            5000000           0           0
Belgium                  0           0           0
Brazil             4000000     4000000           0
Bulgaria           7000000           0           0
Cambodia                 0           0           0
Canada           153150000    42500000    12200000
Chile                    0    26000000           0
China             65000000   227000000    68005000
Czech Republic           0    50000000           0
Denmark            1000000           0           0
France           193700000   106700000    17000000
Germany                  0     2500000           0
Greece                   0           0    18000000
Hong Kong          7000000    36000000           0
India                    0   168026148     4400000
Ireland                  0    13000000           0
Israel                   0      450000           0
Italy                    0    15000000           0
Japan                    0    35000000    75000000
Kenya                15000           0           0
Kyrgyzstan         1400000           0           0
Mexico                   0    28000000     3000000
New Zealand      250350000           0           0
Norway             6600000           0           0
Pakistan                 0     1000000           0
Panama                   0           0    20000000
Romania            5000000      168000           0
Russia            26000000    30000000           0
Slovenia                 0      500000           0
South Africa      29000000           0           0
South Korea       10000000           0    12620000
Spain              8000000           0           0
Switzerland       30000000           0           0
Taiwan                   0    15000000           0
Thailand           9000000           0           0
UK               601640000   510000000   843500000
USA             6525753000  6418910000  4194050000